import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {parseSkill,saveSkill,localSkills} from './skills-store.ts';
const content='---\nname: review-project\ndescription: Review a project brief\nversion: 1.0.0\n---\n\nRead the brief and list missing information.';
test('native metadata and instructions parsed',()=>{const s=parseSkill(content);assert.equal(s.name,'review-project');assert.equal(s.instructions,'Read the brief and list missing information.');});
test('reject traversal, missing body, invalid metadata and oversized data',()=>{for(const s of [content.replace('review-project','../escape'),content.split('\n\n')[0],content.replace('Review a project brief','>'),content+'x'.repeat(131072)])assert.throws(()=>parseSkill(s));});
test('exclusive install, discovery and unchanged uploaded content',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'skills-test-'));try{await saveSkill(root,content);assert.equal(await readFile(path.join(root,'review-project','SKILL.md'),'utf8'),content);assert.equal((await localSkills(root))[0].name,'review-project');await assert.rejects(()=>saveSkill(root,content),{code:'EEXIST'});}finally{await rm(root,{recursive:true,force:true});}});
