'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Agent={id:string;name:string;title?:string;description?:string;role?:string;state?:string;orchestrator?:boolean;runtime_backed?:boolean;max_turns?:number;tool_count?:number;tools?:string[];capabilities?:string[]};
export function AgentsLibrary(){
 const [agents,setAgents]=useState<Agent[]>([]),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/api/v1/agents',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('Could not load agents.');return r.json();}).then(d=>{setAgents(d.agents||[]);setSelected(d.agents?.[0]?.id||'');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[]);
 const current=agents.find(a=>a.id===selected);const filtered=agents.filter(a=>`${a.name} ${a.role} ${a.description} ${(a.capabilities||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="sb-tool"><div className="sb-tool-heading"><p className="sb-label">YOUR CORE ENGINE TEAM</p><h1>Your agents.</h1><p>Inspect each agent’s properties, capabilities and assigned tools from the live runtime.</p></div><div className="sb-library-toolbar"><input aria-label="Search agents" placeholder="Search agents…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{error&&<p role="alert" className="sb-error">{error} <button onClick={()=>location.reload()}>Retry</button></p>}{loading?<p>Loading agents…</p>:<><p className="sb-label">{filtered.length} AGENTS</p><div className="sb-agent-layout"><div className="sb-library-list">{filtered.map(a=><button className="sb-skill-row" key={a.id} aria-pressed={selected===a.id} onClick={()=>setSelected(a.id)}><span><strong>{a.title||a.name}</strong><small>{a.description||a.role}</small></span><span>{a.state||'Unknown'} · {a.tool_count??a.tools?.length??0} tools</span></button>)}{!filtered.length&&<p>No matching agents.</p>}</div>{current&&<article className="sb-agent-detail" aria-label="Agent properties"><p className="sb-label">AGENT PROPERTIES</p><h2>{current.title||current.name}</h2><p>{current.description}</p><dl><dt>ID</dt><dd>{current.id}</dd><dt>Role</dt><dd>{current.role||'Not reported'}</dd><dt>State</dt><dd>{current.state||'Not reported'}</dd><dt>Orchestrator</dt><dd>{current.orchestrator?'Yes':'No'}</dd><dt>Runtime backed</dt><dd>{current.runtime_backed?'Yes':'No'}</dd><dt>Maximum turns</dt><dd>{current.max_turns??'Not reported'}</dd></dl><h3>Capabilities</h3>{current.capabilities?.length?<ul>{current.capabilities.map(c=><li key={c}><code>{c}</code></li>)}</ul>:<p>No capabilities reported.</p>}<h3>Assigned tools ({current.tools?.length??0})</h3><div className="sb-agent-tools">{current.tools?.map(t=><code key={t}>{t}</code>)}</div><Link className="sb-library-action" href={`/dashboard?view=lola&prompt=${encodeURIComponent(`Explain the ${current.name} agent and how I can work with it. Do not execute any tools yet.`)}`}>Ask Lola about this agent ↗</Link></article>}</div></>}</section>;
}
