'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {useRouter} from 'next/navigation';
import { signOut } from '@/app/login/_auth/authService';

type Note={id:string;title:string;kind:string;updated?:string;degree:number};
type Project={id:string;number:string;name:string;openTasks:number;currentPhase?:string;nextAction?:string};
type Task={id:string;title:string;status:string;projectNumber?:string;dueDate?:string};
const nav=[['Overview','/dashboard'],['Brain graph','/dashboard/brain'],['Knowledge','/dashboard/knowledge'],['Ideas','/dashboard/ideas'],['Projects','/dashboard/projects'],['Tasks','/dashboard/tasks'],['Documents','/dashboard/documents'],['Emails','/dashboard/emails'],['Contacts','/dashboard/contacts']];
async function read(url:string){const r=await fetch(url);if(!r.ok)throw new Error(r.status===401?'Sign in again to load your workspace.':'This source is temporarily unavailable.');return r.json();}
export function SecondBrain(){
 const router=useRouter();
 const [notes,setNotes]=useState<Note[]>([]),[projects,setProjects]=useState<Project[]>([]),[tasks,setTasks]=useState<Task[]>([]);
 const [mode,setMode]=useState<'overview'|'brain'>('overview');
 const [loading,setLoading]=useState(true),[errors,setErrors]=useState<string[]>([]),[query,setQuery]=useState(''),[capture,setCapture]=useState(''),[notice,setNotice]=useState('');
 const search=useRef<HTMLInputElement>(null),draft=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{let live=true;Promise.allSettled([read('/api/v1/ais-brain/api/graph'),read('/api/v1/projects'),read('/api/v1/tasks?view=all')]).then(results=>{if(!live)return;const [g,p,t]=results;if(g.status==='fulfilled')setNotes(g.value.nodes);if(p.status==='fulfilled')setProjects(p.value.projects);if(t.status==='fulfilled')setTasks(t.value.tasks);setErrors(results.flatMap((r,i)=>r.status==='rejected'?[['Knowledge','Projects','Tasks'][i]+': '+r.reason.message]:[]));setLoading(false);});const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search.current?.focus();}};window.addEventListener('keydown',key);return()=>{live=false;window.removeEventListener('keydown',key);};},[]);
 const recent=[...notes].filter(n=>n.updated).sort((a,b)=>Date.parse(b.updated!)-Date.parse(a.updated!)).slice(0,6);
 const matches=query.trim()?notes.filter(n=>n.title.toLowerCase().includes(query.trim().toLowerCase())):[];
 const active=[...projects].filter(p=>p.openTasks>0).sort((a,b)=>b.openTasks-a.openTasks).slice(0,4);
 const open=tasks.filter(t=>t.status!=='done').slice(0,4);
 function download(){if(!capture.trim())return;const url=URL.createObjectURL(new Blob([capture],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='core-engine-note.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Markdown download started. Keep this note in your vault.');}
 return <div className="sb-shell">
 <aside className="sb-sidebar"><Link href="/dashboard" className="sb-brand"><Image src="/logo.svg" alt="" width={32} height={32}/><span>core engine<small>SECOND BRAIN OS</small></span></Link><div className="sb-workspace"><span className="sb-avatar">CE</span><div>Your workspace<small>Personal knowledge system</small></div></div><p className="sb-label">WORKSPACE</p><nav aria-label="Main navigation">{nav.map(([label,url],i)=><Link key={url} href={url} aria-current={i===0?'page':undefined}><span className="sb-nav-index">{String(i+1).padStart(2,'0')}</span>{label}{i===1&&<span className="sb-arrow">↗</span>}</Link>)}</nav><div className="sb-sidebar-bottom"><Link href="/dashboard?view=spatial">Spatial workspace <span>↗</span></Link><small>Explore the existing agent tools</small><button onClick={async()=>{await signOut();router.push('/login');}}>Sign out</button></div></aside>
 <main className="sb-main"><header className="sb-top"><span>Workspace <span className="sb-slash">/</span> <strong>{mode==='brain'?'Brain graph':'Overview'}</strong></span><div className="sb-mode" aria-label="Workspace view"><button aria-pressed={mode==='overview'} onClick={()=>setMode('overview')}>Overview</button><button aria-pressed={mode==='brain'} onClick={()=>setMode('brain')}>Explore Brain</button></div><button className="sb-capture-button" onClick={()=>{setMode('overview');setTimeout(()=>draft.current?.focus(),50);draft.current?.scrollIntoView({behavior:'smooth',block:'center'});}}>+ Capture a thought</button></header>
 {mode==='brain'?<section><div className="sb-graph-help"><span>Search a node · filter sources · select to inspect · scroll to zoom</span><Link href="/dashboard/brain">Full screen ↗</Link></div><iframe className="sb-graph-frame" title="Interactive Brain graph" src="/api/v1/ais-brain/"/></section>:<div className="sb-content"><div className="sb-intro"><p className="sb-label">A PLACE TO THINK. A SYSTEM TO ACT.</p><h1>Your mind, connected.</h1><p>Find what you know. Make room for what comes next.</p></div>
 <section className="sb-search-section" aria-label="Search knowledge"><div className="sb-search"><span aria-hidden="true">⌕</span><input ref={search} aria-label="Search your knowledge" placeholder="Search your knowledge, ideas, and connections…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ / Ctrl K</kbd></div>{query.trim()&&<div className="sb-results" aria-live="polite"><p>{loading?'Loading knowledge…':`${matches.length} results`}</p>{matches.slice(0,30).map(n=><Link key={n.id} href={`/dashboard/brain?node=${encodeURIComponent(n.id)}`}><span>{n.title}</span><small>{n.kind} ↗</small></Link>)}{matches.length>30&&<p>Showing the first 30. Refine your search to narrow the results.</p>}</div>}</section>
 {errors.length>0&&<div role="alert" className="sb-error">{errors.map(e=><p key={e}>{e}</p>)}<button onClick={()=>location.reload()}>Retry loading</button></div>}
 <div className="sb-columns"><div className="sb-primary"><section className="sb-section"><div className="sb-section-head"><h2>Recently updated</h2><Link href="/dashboard/knowledge">All knowledge ↗</Link></div><p className="sb-section-sub">Pick up a thread from your knowledge base.</p><div className="sb-note-list">{loading?<p className="sb-empty">Loading your knowledge…</p>:recent.length===0?<p className="sb-empty">No dated knowledge is available yet.</p>:recent.map(n=><Link className="sb-note" key={n.id} href={`/dashboard/brain?node=${encodeURIComponent(n.id)}`}><span className="sb-note-icon">{n.kind==='idea'?'I':'N'}</span><span className="sb-note-title">{n.title}<small>{n.kind.replaceAll('-',' ')} · {n.degree} connections</small></span><time>{new Date(n.updated!).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</time><span className="sb-arrow">↗</span></Link>)}</div></section>
 <section className="sb-section"><div className="sb-section-head"><h2>Projects in motion</h2><Link href="/dashboard/projects">All projects ↗</Link></div><div className="sb-projects">{loading?<p className="sb-empty">Loading projects…</p>:active.length===0?<p className="sb-empty">No projects with open tasks.</p>:active.map(p=><Link className="sb-project" key={p.id} href={`/dashboard/projects/${encodeURIComponent(p.number)}`}><small>{p.number}</small><h3>{p.name}</h3><p>{p.currentPhase||'Project workspace'}</p><footer><span>{p.openTasks} open tasks</span><span>↗</span></footer></Link>)}</div></section></div>
 <aside className="sb-secondary"><Link href="/dashboard/brain" className="sb-brain"><span className="sb-label">THE BIGGER PICTURE</span><h2>Follow the<br/>connections.</h2><p>Explore the ideas, sources, and projects that connect your work.</p><span className="sb-brain-link">Open Brain graph <b>↗</b></span></Link>
 <section className="sb-task-section"><div className="sb-section-head"><h2>Next actions</h2><Link href="/dashboard/tasks">View all ↗</Link></div>{loading?<p className="sb-empty">Loading tasks…</p>:open.length===0?<p className="sb-empty">No open tasks.</p>:open.map(t=><Link className="sb-task" href="/dashboard/tasks" key={t.id}><span className="sb-task-dot"/><span>{t.title}<small>{t.projectNumber||t.status}{t.dueDate?` · Due ${t.dueDate}`:''}</small></span></Link>)}</section>
 <section className="sb-capture"><div className="sb-section-head"><h2>Quick capture</h2><span className="sb-label">MARKDOWN</span></div><textarea ref={draft} aria-label="Capture a thought" placeholder="An idea, a question, a loose thread…" value={capture} onChange={e=>{setCapture(e.target.value);setNotice('');}}/><div className="sb-capture-foot"><small>Download to your vault</small><button onClick={download} disabled={!capture.trim()}>Download note ↓</button></div>{notice&&<p role="status">{notice}</p>}</section></aside></div>
 <footer className="sb-footer"><span>CORE ENGINE <span className="sb-slash">/</span> SECOND BRAIN</span><span>Your knowledge. Within reach.</span></footer></div>}</main></div>;
}
