'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
type Skill={name:string;description:string;version?:string;scope?:string;source?:string;content?:string};
export function SkillsTools({section}:{section:'skills'|'tools'}){
 const [skills,setSkills]=useState<Skill[]>([]),[tools,setTools]=useState<string[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[form,setForm]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState(''),[instructions,setInstructions]=useState(''),[upload,setUpload]=useState(''),[fileName,setFileName]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[selected,setSelected]=useState<Skill|null>(null);
 const fileInput=useRef<HTMLInputElement>(null);
 async function load(){const r=await fetch(`/api/v1/${section}`);const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}
 useEffect(()=>{let active=true;fetch(`/api/v1/${section}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}).then(d=>{if(active){setSkills(d.skills||[]);setTools(d.tools||[]);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[section]);
 async function save(){setBusy(true);setError('');setNotice('');try{const content=fileName?upload:`---\nname: ${name}\ndescription: ${description.replace(/[\r\n]/g,' ')}\nversion: 1.0.0\nsource: native\n---\n\n${instructions}\n`;const r=await fetch('/api/v1/skills',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});const data=await r.json();if(!r.ok)throw new Error(data.error);setNotice(`${data.name} installed. It has not been automatically activated.`);setForm(false);setUpload('');setFileName('');setName('');setDescription('');setInstructions('');const list=await load();setSkills(list.skills||[]);}catch(e){setError(e instanceof Error?e.message:'Could not save skill.');}finally{setBusy(false);}}
 async function chooseFile(file:File|undefined){if(!file)return;setError('');if(!file.name.toLowerCase().endsWith('.md')||file.size>128*1024){setError('Choose a Markdown (.md) file up to 128 KB.');return;}try{const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());setUpload(text);setFileName(file.name);setForm(true);}catch{setError('The file must contain UTF-8 text.');}finally{if(fileInput.current)fileInput.current.value='';}}
 const skillList=skills.filter(s=>`${s.name} ${s.description}`.toLowerCase().includes(query.toLowerCase()));const toolList=tools.filter(t=>t.toLowerCase().includes(query.toLowerCase()));
 return <section className="sb-tool"><div className="sb-tool-heading"><p className="sb-label">YOUR WORKSPACE CAPABILITIES</p><h1>{section==='skills'?'Skills library.':'Tools library.'}</h1><p>{section==='skills'?'Reusable instructions for Core Engine. Create your own or import a SKILL.md file.':'Explore the tools registered in Core Engine. Ask Lola when you want to use or extend them.'}</p></div><div className="sb-library-toolbar"><input aria-label={`Search ${section}`} placeholder={`Search ${section}…`} value={query} onChange={e=>setQuery(e.target.value)}/>{section==='skills'?<><button onClick={()=>{setUpload('');setFileName('');setForm(true);setError('');}}>Create skill</button><button onClick={()=>fileInput.current?.click()}>Upload skill</button><input ref={fileInput} type="file" accept=".md,text/markdown" aria-label="Upload skill file" hidden onChange={e=>void chooseFile(e.target.files?.[0])}/></>:<Link className="sb-library-action" href="/dashboard?view=lola&prompt=Help%20me%20design%20a%20new%20Core%20Engine%20tool.%20Ask%20what%20it%20should%20do%20before%20creating%20anything.">Request a tool with Lola ↗</Link>}</div>{error&&<p role="alert" className="sb-error">{error}<button onClick={()=>location.reload()}>Reload</button></p>}{notice&&<p role="status">{notice}</p>}{form&&section==='skills'&&<form className="sb-skill-form" onSubmit={e=>{e.preventDefault();void save();}}><h2>{fileName?`Review ${fileName}`:'Create a skill'}</h2>{fileName?<><p>Review the instructions before installing. Existing names cannot be overwritten.</p><label>Markdown content<textarea value={upload} onChange={e=>setUpload(e.target.value)} required/></label></>:<><label>Name<input required pattern="[a-z0-9][a-z0-9-]{0,63}" maxLength={64} placeholder="project-review" value={name} onChange={e=>setName(e.target.value)}/></label><label>Description<input required maxLength={500} placeholder="When should this skill be used?" value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Instructions<textarea required placeholder="Describe the steps, inputs and expected result…" value={instructions} onChange={e=>setInstructions(e.target.value)}/></label></>}<div><button disabled={busy}>{busy?'Installing…':'Install skill'}</button><button type="button" disabled={busy} onClick={()=>setForm(false)}>Cancel</button></div></form>}
 {loading?<p>Loading {section}…</p>:section==='skills'?<><p className="sb-label">{skillList.length} SKILLS</p><div className="sb-library-list">{skillList.length===0&&<p className="sb-empty">{query?'No matching skills.':'No skills installed yet. Create one or upload a Markdown file to get started.'}</p>}{skillList.map(s=><button className="sb-skill-row" key={`${s.scope}:${s.name}`} onClick={()=>setSelected(s)}><span><strong>{s.name}</strong><small>{s.description}</small></span><span>{s.version||'Skill'} ↗</span></button>)}</div></>:<><p className="sb-label">{toolList.length} TOOLS</p><div className="sb-library-list">{toolList.length===0&&<p className="sb-empty">No matching tools.</p>}{toolList.map(t=><div className="sb-tool-row" key={t}><code>{t}</code><Link href={`/dashboard?view=lola&prompt=${encodeURIComponent(`Explain what the ${t} tool does and how I can use it. Do not execute it yet.`)}`}>Ask Lola ↗</Link></div>)}</div></>}
 {selected&&section==='skills'&&<div className="sb-skill-detail"><button onClick={()=>setSelected(null)}>Close details</button><h2>{selected.name}</h2><p>{selected.description}</p><p>{selected.scope} · {selected.version||'No version'}</p>{selected.content?<pre>{selected.content}</pre>:<p>Instructions for this skill are managed by the Core Engine runtime.</p>}</div>}</section>;
}
