'use client';
import {useEffect,useRef,useState} from 'react';
import {TaskRow} from '../_work/TaskRow';
import type {TaskListItem} from '@/lib/repos/tasks';
import '../_work/work.css';

export function LolaChat(){
 const [messages,setMessages]=useState<{role:string;text:string}[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>{const prompt=new URLSearchParams(location.search).get('prompt');if(prompt){queueMicrotask(()=>setInput(prompt.slice(0,2000)));}return()=>controller.current?.abort();},[]);
 async function send(){if(busy||!input.trim())return;const message=input.trim();setInput('');setError('');setMessages(m=>[...m,{role:'You',text:message}]);setBusy(true);controller.current=new AbortController();try{const r=await fetch('/api/v1/lola/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message}),signal:controller.current.signal});const raw=await r.text();let data;try{data=JSON.parse(raw);}catch{throw new Error('The connection to Lola was interrupted. Your message is preserved below; check its result before sending again.');}if(!r.ok||data.error)throw new Error(data.error||'Could not reach Lola.');if(!data.reply)throw new Error('Lola returned no reply.');setMessages(m=>[...m,{role:'Lola',text:data.reply}]);}catch(e){setError(e instanceof Error&&e.name==='AbortError'?'Request stopped.':e instanceof Error?e.message:'Could not reach Lola.');setInput(message);}finally{setBusy(false);}}
 return <section className="sb-tool"><div className="sb-tool-heading"><p className="sb-label">YOUR CORE ENGINE ASSISTANT</p><h1>Talk with Lola.</h1><p>Ask a question or give Lola a task.</p></div><div className="sb-chat-log" role="log" aria-label="Conversation with Lola" aria-live="polite">{messages.length===0?<p className="sb-empty">Start a conversation. Lola’s responses will appear here.</p>:messages.map((m,i)=><article className="sb-chat-message" data-role={m.role} key={i}><strong>{m.role}</strong><p>{m.text}</p></article>)}{busy&&<p role="status">Lola is working…</p>}</div>{error&&<p role="alert" className="sb-error">{error}</p>}<form className="sb-chat-form" onSubmit={e=>{e.preventDefault();void send();}}><label htmlFor="lola-message">Message Lola</label><textarea id="lola-message" value={input} onChange={e=>setInput(e.target.value)} placeholder="What would you like to work on?" disabled={busy}/><div><button type="submit" disabled={busy||!input.trim()}>Send to Lola</button>{busy&&<button type="button" onClick={()=>controller.current?.abort()}>Stop waiting</button>}</div></form></section>;
}
function dateKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function dueKey(raw:string|null){if(!raw)return '';const iso=raw.match(/^(\d{4}-\d{2}-\d{2})/);if(iso)return iso[1];const m=raw.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?`${m[3]}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`:'';}
export function TaskCalendar(){
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[selected,setSelected]=useState(()=>dateKey(new Date())),[tasks,setTasks]=useState<TaskListItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[unscheduled,setUnscheduled]=useState(false);
 async function load(){try{const r=await fetch('/api/v1/tasks?view=all');if(!r.ok)throw new Error('Could not load calendar tasks.');const data=await r.json();setError('');setTasks(data.tasks);}catch(e){setError(e instanceof Error?e.message:'Calendar unavailable');}finally{setLoading(false);}}
 useEffect(()=>{let active=true;fetch('/api/v1/tasks?view=all').then(async r=>{if(!r.ok)throw new Error('Could not load calendar tasks.');return r.json();}).then(data=>{if(active)setTasks(data.tasks);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 const first=(month.getDay()+6)%7,days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
 const shown=tasks.filter(t=>unscheduled?!dueKey(t.dueDate):dueKey(t.dueDate)===selected);
 return <section className="sb-tool"><div className="sb-tool-heading"><p className="sb-label">MAKE ROOM FOR WHAT MATTERS</p><h1>Your calendar.</h1><p>Task due dates, connected to your projects. Select a day to review or edit its tasks.</p></div><div className="sb-calendar-toolbar"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} aria-label="Previous month">←</button><h2>{month.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h2><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} aria-label="Next month">→</button><button onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));setSelected(dateKey(now));setUnscheduled(false);}}>Today</button><button onClick={()=>setUnscheduled(true)} aria-pressed={unscheduled}>Unscheduled ({tasks.filter(t=>!dueKey(t.dueDate)).length})</button></div>{error&&<p role="alert" className="sb-error">{error}<button onClick={()=>void load()}>Retry</button></p>}<div className="sb-calendar-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><span className="sb-day-label" key={d}>{d}</span>)}{Array.from({length:first},(_,i)=><span key={`blank${i}`}/>)}{Array.from({length:days},(_,i)=>{const day=i+1,key=dateKey(new Date(month.getFullYear(),month.getMonth(),day)),count=tasks.filter(t=>dueKey(t.dueDate)===key).length;return <button key={key} aria-label={`${key}, ${count} tasks`} aria-pressed={!unscheduled&&selected===key} className="sb-calendar-day" onClick={()=>{setSelected(key);setUnscheduled(false);}}><span>{day}</span>{count>0&&<small>{count} tasks</small>}</button>;})}</div><div className="sb-agenda"><h2>{unscheduled?'Unscheduled tasks':selected}</h2>{loading?<p>Loading tasks…</p>:shown.length===0?<p className="sb-empty">No tasks for this selection.</p>:shown.map(t=><TaskRow key={`${t.id}:${t.title}:${t.dueDate}:${t.priority}`} task={t} onUpdated={load}/>)}</div></section>;
}
